{% set name = "methodtools" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e213439dd64cfe60213f7015da6efe5dd4003fd89376db3baa09fe13ec2bb0ba

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - wirerope >=0.4.7

test:
  requires:
    - python {{ python_min }}
  imports:
    - methodtools

about:
  home: https://github.com/youknowone/methodtools
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Expand standard functools to methods
  dev_url: https://github.com/youknowone/methodtools

extra:
  recipe-maintainers:
    - timkpaine
